from flask import Flask, request, jsonify, send_from_directory
from groq import Groq

app = Flask(__name__)
import os
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

@app.route('/')
def home():
    return send_from_directory('.', 'index.html')

@app.route('/generate', methods=['POST'])
def generate():
    topic = request.json['topic']
    
    chat = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        max_tokens=8000,
        messages=[
            {"role": "user", "content": f"""Create visually stunning and comprehensive study notes on the topic: {topic}

Return ONLY a complete HTML page with these requirements:

1. Dark theme: background #0f0f13, cards #1a1a24, text #e8e8f0
2. A clean header with the topic name in purple (#7F77DD)
3. Content split into clearly styled sections with colored headers
4. Key terms highlighted in purple boxes
5. Important facts in glowing bordered callout boxes
6. Tables where relevant with dark styling
7. A quick-revision summary box at the end
8. Footer saying 'Generated by ur notes buddy'
9. Make it detailed, exam-focused, and cover all subtopics thoroughly

Return complete HTML only, no explanation."""}
        ]
    )
    
    return jsonify({"html": chat.choices[0].message.content})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
