import os
import random
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from groq import Groq

app = Flask(__name__)
CORS(app)

keys = [
    os.environ.get("GROQ_KEY_1"),
    os.environ.get("GROQ_KEY_2"),
    os.environ.get("GROQ_KEY_3"),
]

@app.route("/")
def home():
    return send_from_directory(".", "index.html")

@app.route("/practice")
def practice_page():
    return send_from_directory(".", "practice.html")

@app.route("/generate", methods=["POST"])
def generate():
    topic = request.json["topic"]
    prompt = f"""Create visually stunning and comprehensive study notes on the topic: {topic}

Return ONLY a complete HTML page with these requirements:

1. Dark theme: background #0f0f13, cards #1a1a24, text #e8e8f0
2. A clean header with the topic name in purple (#7F77DD)
3. Content split into clearly styled sections with colored headers
4. Key terms highlighted in purple boxes
5. Important facts in glowing bordered callout boxes
6. Tables where relevant with dark styling
7. A quick-revision summary box at the end
8. Footer saying Generated by ur notes buddy
9. Make it detailed, exam-focused, and cover all subtopics thoroughly
10. Add a Download as PDF button fixed at top-right styled in purple that calls window.print() when clicked. Also add print CSS that hides the button when printing.
11. Add a back button at top-left that says back to Home as an anchor tag linking to /

Return complete HTML only, no explanation."""

    random.shuffle(keys)
    for key in keys:
        try:
            client = Groq(api_key=key)
            chat = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                max_tokens=8000,
                messages=[{"role": "user", "content": prompt}]
            )
            html_output = chat.choices[0].message.content
            html_output = html_output.replace("```html", "").replace("```", "")
            return jsonify({"html": html_output})
        except Exception:
            continue

    return jsonify({"error": "All keys rate limited. Try again later."}), 500

@app.route("/practice", methods=["POST"])
def practice():
    topic = request.json["topic"]
    exam = request.json["exam"]

    if exam == "neet":
        prompt = f"""Create a NEET practice worksheet on the topic: {topic}

Generate 30-40 MCQs if it is a full chapter, 15-20 if it is a subtopic.
Format as clean HTML with dark theme (background #0f0f13, cards #1a1a24, text #e8e8f0).
Each question should:
- Be numbered
- Have 4 options (A, B, C, D)
- Show the correct answer at the end in a highlighted box
- Be NEET difficulty level
- Cover all important concepts of the topic

Add a header saying NEET Practice — {topic}
Add a print button at top right calling window.print().
Add a back to home link at top left linking to /
Return only HTML, no explanation."""

    elif exam == "jee":
        prompt = f"""Create a JEE practice worksheet on the topic: {topic}

Generate 25-35 MCQs at JEE Main and Advanced difficulty.
Format as clean HTML with dark theme (background #0f0f13, cards #1a1a24, text #e8e8f0).
Each question should:
- Be numbered
- Have 4 options (A, B, C, D)
- Show the correct answer at the end
- Include numerical and calculation based questions where relevant
- Be JEE difficulty level

Add a header saying JEE Practice — {topic}
Add a print button at top right calling window.print().
Add a back to home link at top left linking to /
Return only HTML, no explanation."""

    else:
        prompt = f"""Create a Board exam practice worksheet on the topic: {topic}

Generate a mix of:
- 10-15 short answer questions (2-3 marks)
- 8-10 long answer questions (5 marks)
- 5-8 very short answer questions (1 mark)

Format as clean HTML with dark theme (background #0f0f13, cards #1a1a24, text #e8e8f0).
Each section clearly labeled.
Include model answers at the end.
Cover CBSE board exam important questions for this topic.

Add a header saying Board Practice — {topic}
Add a print button at top right calling window.print().
Add a back to home link at top left linking to /
Return only HTML, no explanation."""

    random.shuffle(keys)
    for key in keys:
        try:
            client = Groq(api_key=key)
            chat = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                max_tokens=8000,
                messages=[{"role": "user", "content": prompt}]
            )
            html_output = chat.choices[0].message.content
            html_output = html_output.replace("```html", "").replace("```", "")
            return jsonify({"html": html_output})
        except Exception:
            continue

    return jsonify({"error": "All keys rate limited. Try again later."}), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
